apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.17.0
          ports:
            - containerPort: 5601
          env:
            - name: SERVER_NAME
              value: kibana
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN
              value: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpSWXNwQnRSRlRNNnZ0ZDVyTmlPXzZB
            - name: XPACK_SECURITY_ENCRYPTIONKEY
              value: KMbIUEmceO/wCMlSv66rjKg8GTvdt4kkO4hY4Cp991E=
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              value: HXeldtxFPKSua7FLBP7yO/20f02Yk3SiEnyTAe2pzfU=
            - name: XPACK_REPORTING_ENCRYPTIONKEY
              value: +qJ7jH1HuQcFWRQJymsoF7Csu7tN/GoUyHSY2P4up5I=
            - name: NODE_OPTIONS
              value: --openssl-legacy-provider=false
          args:
            - "bin/kibana"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
