apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elk
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        # - name: fix-backup-permissions
        #   image: busybox
        #   command: ["sh", "-c", "chown -R 1000:1000 /mount/backups && chmod -R 770 /mount/backups"]
        #   volumeMounts:
        #     - name: backup-mount
        #       mountPath: /mount/backups
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.enrollment.enabled
              value: "true"
            - name: ELASTIC_PASSWORD
              value: "elkpassword"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
            # - name: backup-mount
            #   mountPath: /mount/backups
      # volumes:
      #   - name: backup-mount
      #     hostPath:
      #       path: /mount/backups    # Path on the host machine
      #       type: DirectoryOrCreate
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
